name: Deploy ASP.Net app to an Azure Web App
env:
  AZURE_WEBAPP_NAME: web-mfo-01    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
on:
  workflow_dispatch:
    inputs:
      artifact_workflow_number:
        required: true
        description: 'workflow run number where artifacts will be downloaded'
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          run_number: ${{ inputs.artifact_workflow_number }}
          name: .net-app
          workflow_conclusion: success
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}